### ISSUE TITLE
Enhancement: Create selection sets for each change type

### ISSUE THREAD

**Issue by andydandy74** [mattmas/Metamorphosis#10]
And another idea: It would be really useful if changed elements could be added to selection sets (one for each change type) for subsequent use with view filters.

**Comment by mattmas** [comment]
Andreas - try right-clicking on the "middle" nodes in the tree, and it should offer that you can add all the sub-nodes to the selection set (there are some cases, like linked models and deleted elements that don't work, but most do!).

**Comment by andydandy74** [comment]
Nice, hadn't tried right-clicking - easy enough to manually save a selection set like that.

**Comment by thazell** [comment]
@andydandy74 can selection sets include elements in a link or only elements in the host model?

**Comment by andydandy74** [comment]
@thazell - I honestly don't know and never tried but looking at the ```SelectionFilterElement``` class I would be quite surprised if selection sets could include elements from linked models. Does Metamorphosis detect changes in linked models, too? I hadn't actually expected/tried that.

**Comment by mattmas** [comment]
Metamorphosis runs on one model at a time, but it is able to run on an in-memory model that is linked into the current model. I'll tell you that right now, the selection option will refuse if the current model is a linked model.

**Comment by thazell** [comment]
@andydandy74 yes the "model" selected can be the active or host model as well as the linked model.  Obviously due to api limitations changes appear differently between the two.
