### ISSUE TITLE
Can not run

### ISSUE THREAD

**Issue by pete1352** [mattmas/Metamorphosis#12]
![image](https://cloud.githubusercontent.com/assets/25832022/23045612/0a9bb16a-f46b-11e6-9334-ce23a9b15e5e.png)

After downloading and copying the files to the folder on my C drive, get the following load error in 2017 and 2016 when opening Revit.

**Comment by thazell** [comment]
Did you unblock the .dll?
Look at issue :https://github.com/mattmas/Metamorphosis/issues/6

**Comment by thazell** [comment]
https://github.com/mattmas/Metamorphosis/issues/6 #

**Comment by pete1352** [comment]
I did and tried again but the same message came up

**Comment by pete1352** [comment]
that worked

**Comment by mattmas** [comment]
I recommend using the installer (I should take away the DLLs now that we have one).
