### ISSUE TITLE
Enhancement - comparison settings

### ISSUE THREAD

**Issue by pete1352** [mattmas/Metamorphosis#13]
It would be great to be able to save out the categories selected for comparison between models so you could use the same custom setup on future runs.

**Comment by mattmas** [comment]
Agreed, I've been thinking about that as well? what do you think it should be called in the User Interface to make it understandable?  "Previous Settings"?   (it would have a drop-down box with a named list of previous settings, like "Model Only" "Drawing Only", etc) - and you could save more...

**Comment by pete1352** [comment]
Comparison selection setup

Comparison configuration

Selection sets

Matt Petermann, LEED AP, CDT
Digital Practice Manager, Associate
Perkins+Will

**Comment by thazell** [comment]
That is really a great idea.  Would it live in an XML file or similar so it could be shared with other users?  Example:  once I come up with a typical setting that people would use in our office, I could update a file on their computer that would have "my preferred/recommended run settings?" Obviously they could overwrite with their own settings, but it might give a starting point.  What about "Previously selected categories" for a specific name?

**Comment by mattmas** [comment]
Added a new Save dialog that lets you save your current category settings as a file.
(settings files are stored in the %COMMONAPPDATA% or %USERAPPDATA%\Metamorphosis folder, depending on your permissions.
Also added an entry to the regular setting.xml file if you wanted to make a particular setting name the default.

Version 1.0.7 posted.

**Comment by thazell** [comment]
Very Cool!  Can't wait to try it out!
