### ISSUE TITLE
Feature request: Support category types in category settings

### ISSUE THREAD

**Issue by andydandy74** [mattmas/Metamorphosis#15]
Currently, when saving a complete subtree of categories (e.g. model elements), the settings file stores every category. When loading that setting, the checkbox of that subtree is unchecked (which is confusing to users):
![metamorphosissavedcategories](https://cloud.githubusercontent.com/assets/3014437/24950297/f399ad6a-1f70-11e7-9602-c8603631a80b.PNG)
My proposal would be the following:
If an entire subtree is selected, do not save every category of that subtree in the settings file. Instead save the ```CategoryType``` using its enum value of CategoryType (http://www.revitapidocs.com/2017/eb96f224-a134-50e6-57e8-32bcb13bee7d.htm). This would also be more robust in terms of dealing with potential category changes in the Revit data model in future Revit versions.

**Comment by mattmas** [comment]
Andreas - check out the new update, I've done more or less what you suggested... If you pick at the CategoryType level, we store that, and restore that checkbox.

**Comment by andydandy74** [comment]
That fixed it. Thanks Matt.
