### ISSUE TITLE
Duplicate JSON files

### ISSUE THREAD

**Issue by andydandy74** [mattmas/Metamorphosis#16]
Checking the "Date stamp output" checkbox in the Compare dialog will result in the creation of two identical JSON files:
![twojsonfiles](https://cloud.githubusercontent.com/assets/3014437/24952956/d4914168-1f79-11e7-89b4-bd64c23f986f.PNG)
XXX-Changes-Latest.json is redundant and therefore should not be created if the above option is selected.
Or am I missing something here?

**Comment by mattmas** [comment]
Andreas - that was actually a specific request, I think, of someone at the original hackathon...
I think it might have had something to do with the handoff to the Dynamo visualization (that it could always be a predictable name for a particular model file - while still having a recorded, date-stamped version of the results).

That said - I'm more than open for community discussion on the topic...

-Matt

**Comment by andydandy74** [comment]
Ah I see. In that case it's probably best to leave it as it is. It's just a minor nuisance anyway.
