### ISSUE TITLE
Error Snapshot in revit 2016

### ISSUE THREAD

**Issue by ThongPhan89** [mattmas/Metamorphosis#20]
Dear Matt,

I'm using Metamorphosis with Revit 2016 and it has an error when I use Snapshot.
![image](https://user-images.githubusercontent.com/28525991/29547168-b73608cc-8722-11e7-9c44-9d150ba2be8b.png)

Please review and check where the false is. Thank you so much!

**Comment by mattmas** [comment]
Hello!
Are you running it on a model that is saved to disk? Or is it perhaps unsaved? Or maybe in A360?

Sent from my iPhone

On Aug 21, 2017, at 11:15 PM, ThongPhan89 <notifications@github.com<mailto:notifications@github.com>> wrote:


Dear Matt,

I'm using Metamorphosis with Revit 2016 and it has an error when I use Snapshot.
[image]<https://user-images.githubusercontent.com/28525991/29547168-b73608cc-8722-11e7-9c44-9d150ba2be8b.png>

Please review and check where the false is. Thank you so much!

**Comment by ThongPhan89** [comment]
I run this model on my company’s server. Have you ever seen that fault before?

**Comment by mattmas** [comment]
I have not. It feels like a situation where you have started a new model (or perhaps opened a model detached?), so that there is no “path” to the current model. Is that possible?

Thanks,
Matt

**Comment by ThongPhan89** [comment]
You’re right about the detached model. So i will try again with central model and tell you the result. Thank you so much for your support!

**Comment by mattmas** [comment]
Or a local copy (not detached).
I’ll try to get a fix into the code so that it doesn’t behave so badly!
-Matt

**Comment by ThongPhan89** [comment]
I've checked and it works normally with central model in revit 2016. But in 2017, I can detach model and take snapshot. I hope you would fix this problem soon. Thank Matt!

**Comment by mattmas** [comment]
Not sure why this has been left open for so long, but it's definitively closed now.
