### ISSUE TITLE
View Previous Compare

### ISSUE THREAD

**Issue by thazell** [mattmas/Metamorphosis#3]
Potential Feature to avoid running a new compare.

**Comment by mattmas** [comment]
Gotcha - so reload the compare results from the JSON file?

**Comment by mattmas** [comment]
FYI - I'm also collecting these ideas on the Project board here: https://github.com/mattmas/Metamorphosis/projects/1

**Comment by mattmas** [comment]
Some cool stuff is in the works, for batch operation, and reading back JSON results later....

**Comment by thazell** [comment]
Very cool.  I have been doing a lot in the last few weeks with journal files to batch open and operate on Revit files.  Curious to see what you have coming down the line...  (sitting on the edge of my seat with excitement)

**Comment by KCMarch** [comment]
Awesome Matt, excited to see these features in action!

Timon, your comment has me curious... so are you setting up a sequence of Revit manipulations then running that as a "macro" across multiple models using the associated journal file?

**Comment by thazell** [comment]
Sent an email, but basically I'm able to launch Revit and run some commands, save and close and repeat.

**Comment by mattmas** [comment]
added a new command for "Previous" where you can load up a previous JSON results file, so we'll close out this one.
