### ISSUE TITLE
Will the change of element IDs effect the output?

### ISSUE THREAD

**Issue by SajithWetta** [mattmas/Metamorphosis#35]
As Revit element IDs are not unique and might change in instances where work-sharing is active I would like to know if you have used the Unique IDs for the comparison?

And is it possible to alter the code to view all the changes rather than the primary change? (maybe as another version of the software)

**Comment by mattmas** [comment]
I can’t recall if we use UniqueIDs or elementIDs, honestly.

But you should be fine, even if we used ElementIDs, so long as you SyncToCentral prior to running the snapshot or compare.

Matt

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
