### ISSUE TITLE
Metamorphosis addin

### ISSUE THREAD

**Issue by ghost** [mattmas/Metamorphosis#36]
The MetamorphosisInstaller.zip contains MetamorphosisInstaller.msi. Is Metamorphosis.addin file available for download?

**Comment by mattmas** [comment]
I'm not sure if I understand what you're getting at - it looks like you posted the contents of the file in the subject?
You can find and download the original version from github from here:
https://github.com/mattmas/Metamorphosis/tree/master/src/MetaInstaller

**Comment by ghost** [comment]
Posting the contents in the subject was an error. Sorry about that. I joined Github today in an effort to download and install Metamorphosis.addin. When I download all I end up with is MetamorphosisInstaller.msi.

I just tried the link you sent me but I still can’t locate the Metamorphosis.addin file. I guess the site is a bit confusing to me. Perhaps you could attach the Metamorphosis.addin file if and when you response to this email?


Thanks for your assistance.

[cid:image001.png@01D5777D.A14B1F50]
[cid:image002.png@01D5777D.A14B1F50]


Randy Patrick
Sr Designer I
U.S.A.
Architecture

[https://media.emailhype.co.uk/00000137-775e531170fbf3fc26aef9554e14e478/images/landline.png]
407-647-7275
[https://media.emailhype.co.uk/00000137-775e531170fbf3fc26aef9554e14e478/images/logo_entity.png]
482 S. Keller Rd. Orlando, FL 32810

[Main Banner Image]<http://go.emailhype.co.uk/00000137-775e531170fbf3fc26aef9554e14e478/>

[https://media.emailhype.co.uk/00000137-775e531170fbf3fc26aef9554e14e478/images/snc_atkins_logo.png]<http://www.atkinsglobal.com/>
Company
[https://media.emailhype.co.uk/00000137-775e531170fbf3fc26aef9554e14e478/images/twitter_company.png]<http://twitter.com/#!/atkinsglobal>
[https://media.emailhype.co.uk/00000137-775e531170fbf3fc26aef9554e14e478/images/linkedin_company.png]<http://www.linkedin.com/company/atkins>
[https://media.emailhype.co.uk/00000137-775e531170fbf3fc26aef9554e14e478/images/facebook_company.png]<http://www.facebook.com/atkinsglobal>
[https://media.emailhype.co.uk/00000137-775e531170fbf3fc26aef9554e14e478/images/youtube_company.png]<http://www.youtube.com/user/wsatkinsplc>
