### ISSUE TITLE
Minor Issue with Column Locations

### ISSUE THREAD

**Issue by thazell** [mattmas/Metamorphosis#5]
Just putting this here as a log. Not a big issue:  Column locations in Revit are not intuitive.  They don't have appropriate "Z" vectors.   The reason I mention this is that here's an example of the move change for columns.  Note:  Green is the column that moved, note how all the arrows are at the datum, even though all the columns that changed are at different elevations.
![image](https://cloud.githubusercontent.com/assets/14113080/21784119/3a2e4ee8-d688-11e6-8251-4b27d42f6b53.png)

**Comment by mattmas** [comment]
So we are picking up the column z location from the level, but not including the level offset? is that what we're saying?

or is the Z-value coming from zero and we need to get both the level and the level offset?

**Comment by thazell** [comment]
The second option: 
The way I have handled column locations in the past is:  first check to see if it's a vertical column, because sloped columns have a location curve, like a beam. Then X and Y from column location.  Z from Level + Offset. (project location and survey location may give different Z - values.)

**Comment by mattmas** [comment]
(fixed this in a recent version).
