### ISSUE TITLE
New versions installation problem

### ISSUE THREAD

**Issue by wrartes** [mattmas/Metamorphosis#6]
I have some problems with the 2016 and 2017 versions; I follow all the installation procedures and when Revit open a warning message show for both versions.

I am using the latest version of the tool.

![2017-01-23 09_17_17-autodesk Revit 2016 - recent files](https://cloud.githubusercontent.com/assets/25300526/22207405/08f336fc-e14d-11e6-92e9-897e29f177f4.png)
.

**Comment by thazell** [comment]
Have older versions loaded on your computer?

**Comment by mattmas** [comment]
This looks like from the older version, where we distributed the DLLs directly.
In that case, you must go to each DLL file and check the file properties - and click the "Unblock" button.

(alternatively, you can just delete both of the versions that you have, and run our new installer from the addin folder. That's what I would recommend.)

**Comment by thazell** [comment]
Thanks Matt!

**Comment by wrartes** [comment]
Thanks Matt for the solution.

William Rivera
Silman
202 333 6230
