### ISSUE TITLE
Color by Elements for one Change Type

### ISSUE THREAD

**Issue by thazell** [mattmas/Metamorphosis#7]
Is there a way we can limit the change types that show up when we hit "Color Elements"

The red seems to take over almost every time I have done it and I think red is parameter change, which I typically don't care about.

**Comment by mattmas** [comment]
Actually, I think we currently have only three colors: Green for new. Blue for Geometry Change. Red for Parameter Change (as well as everything else - Move, Rotate). So we probably need at least one more color.

But are you thinking you'd like to have another pop-up when you go to Color where you pick which kinds of changes you would like to see colored?

-Matt

**Comment by thazell** [comment]
Yes, I'd like to see a popup or something that allows us to select which colors to view. It could be a dropdown or some other user interface option.

**Comment by mattmas** [comment]
Added another dialog box.
quick and dirty.

**Comment by mattmas** [comment]
(version 1.0.5)

**Comment by thazell** [comment]
Solid!  Thanks Matt you rock!
