### ISSUE TITLE
2017

### ISSUE THREAD

**Issue by thazell** [mattmas/Metamorphosis#8]
![image](https://cloud.githubusercontent.com/assets/14113080/22669025/f37c9634-ec90-11e6-8ea9-480f0b450c93.png)

**Comment by thazell** [comment]
I seem to still be able to make a snapshot, however I get the above message when I do.  Not sure wha't causing it, but I'd be glad to troubleshoot if that helps

**Comment by thazell** [comment]
Not sure if it is related, but when I reviewed the compare no "moved elements" were shown and the AVFs weren't showing up for deleted objects.  These may be unrelated

**Comment by mattmas** [comment]
Weird, I can see where the error is, but I can't quite figure out what it might be...
oh - wait... Any chance that there's a single quote in one of the Level Names?
(if not, perhaps can you send me your model?).

**Comment by thazell** [comment]
I looked through the levels and didn't find anything.  Sadly, can't share the model.

**Comment by thazell** [comment]
I ran the compare backwards and it worked.

**Comment by thazell** [comment]
Could it be workset related?  One of the models wasn't workshared

**Comment by mattmas** [comment]
Doesn't seem like it could be workshare related. Something model-specific in the level names or something odd about the geometry that we're not handling in the snapshot.

(the running in reverse option is clever - it works because whatever it didn't like in the old model is gone in the new model).

**Comment by thazell** [comment]
The reverse compare had all the change types.  The first compare only had 3.

**Comment by mattmas** [comment]
The first compare had an error when documenting the geometry in the snapshot – as such, I don’t know how well you can trust the snapshot.
-Matt

**Comment by wynged** [comment]
Hey all, I was getting this error as well, and a very strange thing seemed to fix it.  The model I was testing it could not find the central model.  
Re-saving as central seemed to solve this issue.  Not sure if it's the root of the issue, but it's an important thing to note, maybe in a readme.

**Comment by mattmas** [comment]
aha - that IS interesting. I'll explore.

**Comment by thazell** [comment]
@wynged That is a good thing to mention, I have found that it works best when a model is not detached from central.

**Comment by andydandy74** [comment]
I can consistently reproduce this on any model I touch, also on the basic arch. model that ships with Revit so I would rule out worksharing as the cause.

**Comment by mattmas** [comment]
Andreas - I suspect that your issue is related to the German environment / Decimal Separator issue - I missed dealing with that in one spot. I don't know if it's the same issue as Timon.
I'm preparing an update that fixes that, as well as adds some additional optional logging so that we can solve this once-and-for-all.

**Comment by thazell** [comment]
All our work is in English, it may be related, but I don't see the connection.  Sounds like to logging might help.

**Comment by mattmas** [comment]
Timon - can you try out the newest version with the logging?
You'll need to:
Go to C:\ProgramData\Autodesk\Revit\Addins\<version>\Metamorphosis
Edit the Settings.xml
Change the "LogLevel" entry to "Verbose", then launch Revit.

The log info, after you reproduce the issue, is written to your Revit journal file - can you try again and send it to me?

(reset the LogLevel afterwards, I suspect it slows things down).

**Comment by andydandy74** [comment]
@mattmas - I am happy to report that I do not get these errors any more, Nice work!

**Comment by thazell** [comment]
Doesn't look like I'm seeing that issue, but I didn't log which project that error came up on, so if I see it again, I'll let you know.  btw, the new version is much faster and I like all the new features!
