### ISSUE TITLE
Enhancement: Default colours for change type

### ISSUE THREAD

**Issue by andydandy74** [mattmas/Metamorphosis#9]
Very handy tool, thanks!
It would be great if we could set a different default colour for each change type.

**Comment by mattmas** [comment]
That's a good suggestion. What kind of control do you feel like would be acceptable?
- a configuration file in the install folder?
- a user-specific configuration file?
- a dialog box in the user interface (saving to the user configuration file)?

**Comment by andydandy74** [comment]
I don't think it would be necessary to expose that kind of setting in the UI as it's not something you would change on a daily basis. For deployments a non-user-specific config file would be best, I think.

**Comment by thazell** [comment]
@andydandy74 are you talking about the ability to see color in the dialog box as you scroll through the changes or control over changing red, green, blue for the color overrides of elements in a view?

**Comment by andydandy74** [comment]
@thazell - I'm talking about the colours used for the AVF overlay

**Comment by jessiepurcey** [comment]
I'd also be interested in the ability to change the colors of the overlay.

In addition to, or even without that ability, it would be nice to see some indication of what the colors are in the UI. A simple key could suffice.

**Comment by mattmas** [comment]
I've added a settings.xml file to the install (one in each version of Revit) where you can configure the color values.  The colors are now visible when you choose to color the view (you see them when you pick which change types to show).   Version 1.0.6

**Comment by andydandy74** [comment]
Nice! Much appreciated.

**Comment by jessiepurcey** [comment]
This works great. Thanks for the quick update!
